# Generated by Django 3.2.12 on 2022-02-23 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('McDonalds', 'McDonalds'), ('KFC', 'KFC'), ('Burger King', 'Burger King')], max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('latitude', models.FloatField(max_length=15, verbose_name='latitude')),
                ('longitude', models.FloatField(max_length=15, verbose_name='longitude')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='restaurants_api.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'ordering': ['name'],
            },
        ),
    ]
